project         = "tech-talk-062022"
environment     = "dev"
aws_tag_product = "tech-talk"
aws_tag_env     = "dev"
aws_tag_context = "dev"
aws_tag_type    = "dev"
aws_tag_team    = "matt.jourard@example.com"
